### ISSUE TITLE
Client timeout when building index on large collection

### ISSUE THREAD

**Issue by newnativeabq** [ArangoDB-Community/python-arango#185]
client.db().collection().add_persistent_index() will timeout when attempting to add an index to a large collection.

HTTP API spec suggests a 200 index building should be received almost immediately. 

I will try to reproduce this week.  If anyone has seen similar behavior, please let me know.

FIX:
Regress version to 6.1.0

**Comment by joowani** [comment]
Hi @newnativeabq,

Sounds like this is due to the index building taking longer than the default timeout added to python-arango after version 6.1.0.

Options I can think of:
- Provide the user a way to disable timeout for specific API operations/methods in python-arango (not be a trivial change)
- have ArangoDB return an HTTP 201 (probably not backward compatible)
- Create a new instance of ArangoClient without timeout and create indexes with it only
