### ISSUE TITLE
Transactions Failing on Collection Deletion

### ISSUE THREAD

**Issue by sha-eln** [ArangoDB-Community/python-arango#253]
I'm trying to enable transactions when implementing a truncate-then-update operation. However, when I implement it using the code given in the docs, I get the following warning on the frontend before it times out after 3 attempts:

`WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff80a49f3a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /_db/test/_api/transaction/begin`

When running it with our ArangoDB server URL, I get the following error on the frontend:

`CollectionDeleteError: [HTTP 504] Gateway Time-out`

And on the server:

` upstream timed out (110: Connection timed out) while reading response header from upstream, client: xx, server: xx, request: "DELETE /_db/db_name/_api/collection/Test123 HTTP/1.1", upstream: "[xx/_db/db_name/_api/collection/Test123"](xx/_db/db_name/_api/collection/Test123%22)`

Code to reproduce:
```
from arango import ArangoClient

DB_URL = <server_URL>
DB_USER = <user_name>
DB_PASSWORD = <password>
DB_NAME = <db_name>
COLL_NAME = <coll_name>

client = ArangoClient(DB_URL)

db = client.db(DB_NAME , username=DB_USER, password=DB_PASSWORD)
collection = db.collection(COLL_NAME )

collection = txn_db.collection(COLL_NAME )

txn_db = db.begin_transaction(read=collection.name, write=collection.name)

txn_db.delete_collection(name=collection.name, ignore_missing=True)

txn_db.create_collection(COLL_NAME)

txn_db.commit_transaction()
```

Any assistance on what I am missing or doing wrong would be of great help.

**Comment by apetenchea** [comment]
Hello @sha-eln!

Sorry for the delay in responding to your issue, we truly appreciate your patience. Our team has been heavily occupied with other tasks.

In ArangoDB, creating and deleting collections are operations that can't be done inside a transaction. Transactions are designed to provide atomicity and isolation to data manipulation operations (like insert, update, delete) on existing collections, rather than structural changes to the database itself (like creating or deleting collections).

If you need to empty a collection (i.e., delete all documents but keep the collection itself), you should be able to do that using a [truncate operation](https://docs.python-arango.com/en/main/specs.html#arango.collection.Collection.truncate):
```
db = client.db(DB_NAME , username=DB_USER, password=DB_PASSWORD)
collection = db.collection(COLL_NAME)
collection.truncate()
```

Lastly, while you can truncate a collection inside a transaction, it's important to note that if truncation is all you're doing, a transaction is not necessary. Transactions are typically used to ensure atomicity of multiple interdependent operations.

**Comment by apetenchea** [comment]
Dear @sha-eln,

I believe my answer clears some of the confusion regarding transactions. Therefore, I am going to close this issue. In case you experience any problems with our Python driver, don't hesitate to open a new one.

**Comment by sha-eln** [comment]
@apetenchea Thank you so much for your response! Yes that does clear things up quite a bit. Wishing you all the best. :)
